feat: touchpad-config script installs pkgs

diff --git a/bin/executable_touchpad-config b/bin/executable_touchpad-config
--- a/bin/executable_touchpad-config
+++ b/bin/executable_touchpad-config
@@ -4,7 +4,10 @@ set -euo pipefail
 
 
 # Install X11 deps
-sudo dnf install xorg-x11-drv-libinput libinput-utils xinput
+if ! hash xinput > /dev/null 2>&1 ; then
+  gum log "xinput not found, installing..."
+  sudo dnf install xorg-x11-drv-libinput libinput-utils xinput
+fi
 
 # Try to find any touchpad.
 # Confirmed working on an old Lenovo X1.
@@ -12,13 +15,13 @@ TRACKPAD_ID="$(xinput list | grep -E 'touchpad|Synaptics|TrackPad' -i | head -n1
 
 # Only apply if a touchpad was found
 if [[ -n "$TRACKPAD_ID" ]]; then
-    # Check if this is a Synaptics device
-    if xinput list-props "$TRACKPAD_ID" | grep -q "Synaptics Tap Action"; then
-        xinput set-prop "$TRACKPAD_ID" "Synaptics Tap Action" 1 1 1 1 1 1 1
-    # If it's a libinput device
-    elif xinput list-props "$TRACKPAD_ID" | grep -q "libinput Tapping Enabled"; then
-        xinput set-prop "$TRACKPAD_ID" "libinput Tapping Enabled" 1
-    fi
+  # Check if this is a Synaptics device
+  if xinput list-props "$TRACKPAD_ID" | grep -q "Synaptics Tap Action"; then
+    xinput set-prop "$TRACKPAD_ID" "Synaptics Tap Action" 1 1 1 1 1 1 1
+  # If it's a libinput device
+  elif xinput list-props "$TRACKPAD_ID" | grep -q "libinput Tapping Enabled"; then
+    xinput set-prop "$TRACKPAD_ID" "libinput Tapping Enabled" 1
+  fi
 else
-    >&2 echo "DEBUG: no touchpad found, not configuring"
+  gum log --level warn "no touchpad found, not configuring"
 fi
