fix: fuzzy-lock i3 script

diff --git a/bin/executable_fuzzy-lock b/bin/executable_fuzzy-lock
--- a/bin/executable_fuzzy-lock
+++ b/bin/executable_fuzzy-lock
@@ -4,10 +4,25 @@
 set -euo pipefail
 
 
-# Create tempfile for desktop screenshot
-f="$(mktemp --suffix '.png')"
-trap 'rm -f "$f"' EXIT
-scrot --file "$f"
-# See docs on arg format https://imagemagick.org/Usage/blur/
-convert "$f" -blur 45,15 "$f"
-i3lock -i "$f"
+# Wrap core logic in a function, so we can have a failover.
+# Not sure how DISPLAY works here.
+_fuzzy_lock() {
+    # Create tempfile for desktop screenshot
+    # Using a tempfile always fails. Guessing it's weird
+    # character handling in scrot, but haven't confirmed.
+    # f="$(mktemp --suffix '.png')"
+    # f="$(mktemp --suffix '.png' scrotXXXXX -p /tmp)"
+    # It's not ideal to have a known path here, but on single-user systems
+    # it's acceptable.
+    f="/tmp/scrot.png"
+    # trap 'rm -f "$f"' EXIT
+    scrot --file "$f"
+    # See docs on arg format https://imagemagick.org/Usage/blur/
+    convert "$f" -blur 45,15 "$f"
+    i3lock -i "$f"
+}
+
+if ! _fuzzy_lock ; then
+    >&2 echo "Failed to run fuzzy lock, falling back to simple bg..."
+    i3lock --color 000000
+fi
