feat: fetch-bins script accepts tags

diff --git a/bin/executable_penumbra-fetch-release-bins b/bin/executable_penumbra-fetch-release-bins
--- a/bin/executable_penumbra-fetch-release-bins
+++ b/bin/executable_penumbra-fetch-release-bins
@@ -1,15 +1,26 @@
 #!/bin/bash
-# Download and install binaries for the most recent Penumbra release.
+# Download and install binaries for Penumbra. Defaults to the most recent
+# release, as available in the Github API, but supports older releases too,
+# by specifying the tag name.
 set -euo pipefail
 
 
-# Look up most recent release from GitHub. That's probably what we want.
-# TODO: make the version overrideable, defaulting to latest, but supporting
-# installing older versions, since they all go in their same path, anyway.
+# Create global tempfile for writing API JSON
 f="$(mktemp -p /tmp penumbra-binaries-release-XXXXX)"
-curl -sSfL https://api.github.com/repos/penumbra-zone/penumbra/releases/latest -o "$f"
-# Pilfer tag name so we can use it in messaging
-tag_name="$(jq -r .tag_name "$f")"
+
+# Retrieve the most recent release available on Github.
+function get_latest_release() {
+  curl -sSfL https://api.github.com/repos/penumbra-zone/penumbra/releases/latest -o "$f"
+}
+
+# Retrieve release for a given git tag.
+function get_specific_release() {
+  local t
+  t="${1:-}"
+  shift 1
+  curl -sSfL https://api.github.com/repos/penumbra-zone/penumbra/releases \
+    | jq -e ".[] | select(.tag_name == \"${t}\")" > "$f"
+}
 
 # Parse GitHub Release JSON and extract platform-specific download URLs.
 function get_asset_urls() {
@@ -18,6 +29,30 @@ function get_asset_urls() {
         | grep "$(uname -m)" \
         | grep "$(uname -s)" -i
 }
+
+# Parse args. First arg, if any, is a git tag, otherwise default to latest release.
+sought_tag="${1:-}"
+if [[ -n "$sought_tag" ]] ; then
+  if ! get_specific_release "$sought_tag" ; then
+    >&2 echo "ERROR: Penumbra version not found '$sought_tag'"
+    exit 1
+  fi
+else
+  get_latest_release
+fi
+
+# Pilfer tag name so we can use it in messaging
+tag_name="$(jq -r .tag_name "$f")"
+# Set global vars.
+target_base_dir="/opt/penumbra"
+dest_dir="${target_base_dir}/${tag_name}"
+
+# Attempt idempotence: doesn't really ensure the bins are there,
+# but it's a reasonable assumption.
+if [[ -d "$dest_dir" ]] ; then
+  >&2 echo "Directory for '$tag_name' already exists, skipping..."
+  exit 0
+fi
 
 # Download 'em.
 >&2 echo "Downloading bins for ${tag_name} ..."
@@ -38,18 +73,15 @@ find . -type f -iname '*.tar' -print0 | xargs -0 -P 5 -r -n1 tar -xf
 find . -type f -iname '*.tar.gz' -print0 | xargs -0 -P 5 -r -n1 tar -xf
 
 # Check that dir is writable, otherwise make it so.
-target_base_dir="/opt/penumbra"
 if [[ ! -e "$target_base_dir" || ! -w "$target_base_dir" ]] ; then
     sudo mkdir -p "$target_base_dir"
     sudo chmod 775 "$target_base_dir"
     sudo chown "root:${USER:-}" "$target_base_dir"
 fi
 # Install.
-dest_dir="${target_base_dir}/${tag_name}"
 >&2 echo "Installing binaries to: $dest_dir"
 mkdir -p "$dest_dir"
-# TODO: requires `fd` rather than find.
-fd -t x . -X mv -v -t "$dest_dir"
+find "$d" -type f -executable -exec mv -t "$dest_dir" {} +
 
 # Update latest symlink
 rm -f /opt/penumbra/latest
@@ -60,4 +92,4 @@ ln -sf "$dest_dir" /opt/penumbra/latest
 # sudo setcap CAP_NET_BIND_SERVICE,CAP_NET_ADMIN=+ep "${dest_dir}/pd"
 
 >&2 echo "Provisioned binaries for Penumbra ${tag_name} in:"
-fd -t x . "$dest_dir"
+find "$dest_dir" -type f -executable
