refactor: workstation config overhaul
Trying to get all branches met.

diff --git a/bin/executable_install-workstation b/bin/executable_install-workstation
--- a/bin/executable_install-workstation
+++ b/bin/executable_install-workstation
@@ -19,63 +19,58 @@
 set -ueo pipefail
 
 
+# Filepath that will always exist inside a QubesOS VM.
+QUBES_MARKER_VM_PATH="/usr/share/qubes/marker-vm"
+
+
 # Install the zellij terminal emulator, via custom RPM repo.
-function install_zellij() {
+function _install_zellij_via_copr() {
     sudo dnf copr enable -y varlad/zellij
     sudo dnf install -y zellij
 }
 
 # Install the ghostty terminal application, via custom RPM repo.
-function install_ghostty() {
+function _install_ghostty_via_copr() {
     sudo dnf copr enable -y scottames/ghostty
     sudo dnf install -y ghostty
 }
 
-# Install the swayfx WM, a fork of sway, for tiling support under Wayland.
-# Ignore dead-code lint for shellcheck, because it's not currently used.
-# shellcheck disable=SC2329
-function install_swayfx() {
-    sudo dnf copr enable -y swayfx/swayfx
-    sudo dnf install -y swayfx
-}
-
-# Edit user configurations for Alacritty terminal emulator.
-function configure_alacritty() {
-    >&2 echo "Setting up alacritty..."
-    alacritty_theme_dir="${HOME:?}/.config/alacritty/themes"
-    if [[ ! -d "$alacritty_theme_dir" ]] ; then
-        mkdir -p "$alacritty_theme_dir"
-        git clone https://github.com/alacritty/alacritty-theme "$alacritty_theme_dir"
-    fi
-  }
-
 # Install packages appropriate only for a bare metal Fedora Workstation setup,
 # with ability to customize RPM repos and such. Not appropriate for a VM, where e.g.
 # a full i3 environment is not necessary.
-function configure_hardware_workstation() {
+function configure_hardware_workstation_fedora() {
     # These are helper scripts also installed by chezmoi/dotfiles.
     fedora-install-flatpaks
     fedora-install-rpm-fusion
-    i3-setup
+    _install_zellij_via_copr
+    _install_ghostty_via_copr
+
+    install-nix
+    install-dev-tools
 
     # GUI apps
+    # TODO port these source services from chezmoi?
     systemctl --user enable --now redshift
     systemctl --user enable --now syncthing
 }
 
-# Handle the core dev tools setup for "workstation" role.
-function configure_workstation() {
-    install_zellij
-    install_ghostty
-    # don't install swayfx by default; get used to sway first.
-    # install_swayfx
-    configure_alacritty
-    install-nix
-    install-dev-tools
+# Handle the Configuration inside a QubesVM
+function configure_qubes_vm_fedora() {
+  if [[ ! -e "$QUBES_MARKER_VM_PATH" ]] ; then
+    >&2 echo "ERROR: QubesOS marker missing: $QUBES_MARKER_VM_PATH"
+    return 1
+  fi
+
+  fedora-install-rpm-fusion
+  install_zellij_via_copr
+  install_ghostty_via_copr
+
+  install-nix
+  install-dev-tools
 }
 
-# Run laptop-specific configs, for battery monitoring.
-function configure_laptop() {
+# # Run laptop-specific configs, for battery monitoring.
+function configure_laptop_services() {
     # Files have already been copied, so we can assume the battery-monitor
     # scripts and user-level systemd services are in place.
     systemctl --user daemon-reload
@@ -88,21 +83,22 @@ main() {
     hostnamectl_json="$(hostnamectl status --json pretty)"
     chassis="$(jq -r .Chassis <<< "$hostnamectl_json")"
     hostname="$(jq -r .Hostname <<< "$hostnamectl_json")"
+
     # Hardcode primary workstation name, which often hosts ssh sessions.
     # DISPLAY won't be set, but still consider it a workstation.
     if [[ "$hostname" = "Antigonus" ]] ; then
-        configure_hardware_workstation
-    # All laptops are workstations.
-    elif [[ "$chassis" = "laptop" ]] ; then
-        configure_hardware_workstation
-        configure_laptop
+        configure_hardware_workstation_fedora
     # Desktops, but only if run within a graphical environment.
     # Skips hardware servers.
-    elif [[ "$chassis" = "desktop" ]] && [[ -n "${DISPLAY:-}" ]] ; then
-        configure_hardware_workstation
+    elif [[ "$chassis" = "desktop" && "$fedora_version" ]] && [[ -n "${DISPLAY:-}" || -n "${WAYLAND_DISPLAY:-}" ]]; then
+        configure_hardware_workstation_fedora
+    elif [[ -e "$QUBES_MARKER_VM_PATH" && -n "$fedora_version" ]] ; then
+    configure_qubes_vm_fedora
     fi
 
-    configure_workstation
+    if [[ "$chassis" = "laptop" ]] ; then
+        configure_laptop_services
+    fi
 }
 
 main
