Cleans up bootstrapping flow
Adds a barebones packages.txt install,
off by default. All files installed via
bash, with a few git clones.

Haven't configured git user info yet.

diff --git a/home/bin/ansible-ssh b/home/bin/ansible-ssh
--- a/home/bin/ansible-ssh
+++ b/home/bin/ansible-ssh
@@ -17,14 +17,19 @@ if [[ "$#" -lt 1 ]]; then
     exit 1
 fi
 
+if ! hash jq > /dev/null 2>&1 ; then
+    echo "Error: 'jq' not found!"
+    exit 1
+fi
+
 target_host="$1"
 shift 1
 
-host_addr="$(ansible-inventory --host "$target_host" | yq .ansible_host)"
+host_addr="$(ansible-inventory --host "$target_host" | jq .ansible_host)"
 
 if [[ -z "$host_addr" ]] ; then
     printf 'Could not find IP address for host: %s\n.' "${target_host}"
-    exit 1
+    exit 2
 fi
 
 # Pass extra options to SSH command, e.g. `-l <user>` to change user
